# Generated by Django 3.0.3 on 2020-03-23 01:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 1, 15, 34, 566641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 1, 15, 34, 566104, tzinfo=utc)),
        ),
    ]
