# Generated by Django 3.0.3 on 2020-03-23 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200323_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 1, 38, 40, 921218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 1, 38, 40, 920520, tzinfo=utc)),
        ),
    ]
